aaa = {'api': 'mtop.taobao.rate.detaillist.get',
       'data': {
                'abBucketName': 'default_buckets#-99', 'abCode': 'default_buckets', 'allowInteract': 'true', 'canReport': 'true',
                'configMap': {'card_version': 'old', 'show_comments': 'false'},
                'extraInfo': {'enableFilterCurItem': 'false', 'showImprNewItem': 'false', 'tabMergeImpr': 'false', 'newUserTag': 'true', 'newDetail': 'false', 'impr_showtag': '尺寸合适;质量很好;面料柔软', 'badReviewRate': '0.8%', 'optimizeCopy': 'true', 'newList': 'false', 'impr_showtag_attributeId': '40101000;40161003;40131077', 'impr_showtag_id': '40101000-11;40161003-11;40131077-11', 'newInteraction': 'false', 'showBadTab': 'true', 'recomComment': 'true', 'hideBadCount': 'true', 'impr_showtag_sum': '4;2;2', 'itemCateId': '50010159'},
                'feedAllCount': '800', 'feedAllCountFuzzy': '800+', 'feedAppendCount': '1', 'feedAppendCountFuzzy': '1', 
                'feedBadCount': '1', 'feedBadCountFuzzy': '1',
                'feedGoodCount': '800', 'feedGoodCountFuzzy': '800+', 'feedMediaCount': '2', 'feedMediaCountFuzzy': '2', 'feedNormalCount': '6', 'feedNormalCountFuzzy': '6', 'feedNotGoodCount': '7', 'feedNotGoodCountFuzzy': '7', 'feedPicCount': '2', 'feedPicCountFuzzy': '2', 'feedStoreCount': '0', 'feedVideoCount': '0', 'feedVideoCountFuzzy': '0', 'firstPageTips': '为你展示真实评价', 'foldCount': '859', 'fuzzyRateCount': '800+', 'hasNext': 'true', 
                'imprItemVOS': [
                    {'attributeId': '40101000', 'count': '4', 'fuzzyCount': '4', 'imgCount': '0', 'labelId': '40101000-11', 'status': '1', 'title': '尺寸合适'}, 
                    {'attributeId': '40161003', 'count': '2', 'fuzzyCount': '2', 'imgCount': '0', 'labelId': '40161003-11', 'status': '1', 'title': '质量很好'},
                    {'attributeId': '40131077', 'count': '2', 'fuzzyCount': '2', 'imgCount': '0', 'labelId': '40131077-11', 'status': '1', 'title': '面料柔软'}
                ], 
                'imprNewItemVOS': [], 
                'inviteText': '', 'latestSort': 'true', 
                'questionnaireVO': {'browseReviewCount': '6', 'browseReviewSwitch': 'true', 'icon': 'https://img.alicdn.com/imgextra/i4/O1CN01YIbld52803IZkdgr2_!!6000000007869-2-tps-156-156.png', 'targetUrl': 'https://survey.taobao.com/apps/zhiliao/GgUOVyPgB?formType=vivid_rate_list&item_id=680107621134', 'title': ''},
                'range': '800', 
                'rateList': [
                    {'addCartUrl': 'https://sku.taobao.com/index.htm?itemId=680107621134&bottomMode=ADDCART&asyncApiType=normalBuy&skuId=null', 'allowComment': 'true', 'allowInteract': 'true', 'allowNote': 'false', 'allowReportReview': 'true', 'allowReportUser': 'false', 'allowShieldReview': 'false', 'allowShieldUser': 'false', 'annoy': '1', 'auctionNumId': '680107621134', 'auctionTitle': '纯棉男士卫衣秋季潮牌薄款圆领长袖T恤男学生加绒体恤潮流上衣女', 'copy': 'false', 'createTime': '2024年12月10日', 'createTimeInterval': '2个月前', 'creditLevel': '9',
                     'extraInfoMap': {'userGrade': '5', 'report_url': 'https://market.m.taobao.com/app/msd/buyer-aqcenter/report.html?bizSource=taobao&from=ItemComment&subjectType=ITEM_RATE&subjectId=1257589184335#/index'},
                     'feedback': '评价方未及时做出评价,系统默认好评!', 'feedbackDate': '2024年12月10日', 'formalBlackUser': 'false', 'goldUser': 'false', 'hasDetail': 'true', 'headFrameUrl': '', 'headPicUrl': '//img.alicdn.com/imgextra/i4/O1CN01GbZNxl26Vzotrjqli_!!6000000007668-2-tps-160-160.png', 'id': '1257589184335',
                     'interactInfo': {'alreadyLike': 'false', 'commentCount': '0', 'enableComment': 'true', 'enableLike': 'true', 'enableShare': 'true', 'likeCount': '0', 'readCount': '0'},
                     'own': 'false', 'rateType': '1', 'reduceUserNick': '李**6', 'repeatBusiness': 'false',
                     'share': {'detailShareUrl': 'https://web.m.taobao.com/app/mtb-guang/showcase/transfer?target_page=rate_detail&target_h5=https%3A%2F%2Fh5.m.taobao.com%2Fuser_comment%2Fcomment_detail.html&rateId=1257589184335', 'detailUrl': '//h5.m.taobao.com/tnode/index.htm?tnode=page_ratedetail%40ugc%3fpangesture%3dpullrightexit%26navbarHide%3dtrue%26immersive%3dtrue&rateId=1257589184335&headPic=https%3A%2F%2Fimg.alicdn.com%2Fimgextra%2Fi4%2FO1CN01GbZNxl26Vzotrjqli_%21%216000000007668-2-tps-160-160.png', 'shareSupport': 'false', 'shareURL': '//h5.m.taobao.com/user_comment/comment_detail.html?rateId=1257589184335&sellerId=MX8RHvmQWPkx4vkguMFQbPm*eOm*hXm7-XF8Sv8kuP8QT&isEncode=true'},
                     'skuMap': {}, 'structTagEndSize': '0', 'topRate': '0', 'userId': '0', 'userIndexURL': '', 'userMark': 'tDy7HSb8xH6m66IKAgJe1p8X2z1cl0FNWDCFfZBnkvA=', 'userNick': '李**6', 'userStar': '7', 'userStarPic': 'https://img.alicdn.com/imgextra/i4/O1CN01ZlCYMx1nbVriw6u0S_!!6000000005108-2-tps-92-45.png',
                     'userTagList': [
                         {'extraInfo': {'level': '9'}, 'tagCode': 'credit', 'tagDesc': '信用等级', 'tagIconHeight': '27', 'tagIconPic': 'https://img.alicdn.com/imgextra/i4/O1CN01ZlCYMx1nbVriw6u0S_!!6000000005108-2-tps-92-45.png', 'tagIconWidth': '53'}
                     ]
                     },
                    {'addCartUrl': 'https://sku.taobao.com/index.htm?itemId=680107621134&bottomMode=ADDCART&asyncApiType=normalBuy&skuId=null', 'allowComment': 'true', 'allowInteract': 'true', 'allowNote': 'false', 'allowReportReview': 'true', 'allowReportUser': 'false', 'allowShieldReview': 'false', 'allowShieldUser': 'false', 'annoy': '1', 'auctionNumId': '680107621134', 'auctionTitle': '纯棉男士卫衣秋季潮牌薄款圆领长袖T恤男学生加绒体恤潮流上衣女', 'copy': 'false', 'createTime': '1月1日', 'createTimeInterval': '2个月前', 'creditLevel': '9', 'extraInfoMap': {'userGrade': '5', 'report_url': 'https://market.m.taobao.com/app/msd/buyer-aqcenter/report.html?bizSource=taobao&from=ItemComment&subjectType=ITEM_RATE&subjectId=1260006007986#/index'}, 'feedback': '评价方未及时做出评价,系统默认好评!', 'feedbackDate': '2025年1月1日', 'formalBlackUser': 'false', 'goldUser': 'false', 'hasDetail': 'true', 'headFrameUrl': '', 'headPicUrl': '//img.alicdn.com/imgextra/i4/O1CN01GbZNxl26Vzotrjqli_!!6000000007668-2-tps-160-160.png', 'id': '1260006007986', 'interactInfo': {'alreadyLike': 'false', 'commentCount': '0', 'enableComment': 'true', 'enableLike': 'true', 'enableShare': 'true', 'likeCount': '0', 'readCount': '0'}, 'own': 'false', 'rateType': '1', 'reduceUserNick': '水**妞', 'repeatBusiness': 'false', 'share': {'detailShareUrl': 'https://web.m.taobao.com/app/mtb-guang/showcase/transfer?target_page=rate_detail&target_h5=https%3A%2F%2Fh5.m.taobao.com%2Fuser_comment%2Fcomment_detail.html&rateId=1260006007986', 'detailUrl': '//h5.m.taobao.com/tnode/index.htm?tnode=page_ratedetail%40ugc%3fpangesture%3dpullrightexit%26navbarHide%3dtrue%26immersive%3dtrue&rateId=1260006007986&headPic=https%3A%2F%2Fimg.alicdn.com%2Fimgextra%2Fi4%2FO1CN01GbZNxl26Vzotrjqli_%21%216000000007668-2-tps-160-160.png', 'shareSupport': 'false', 'shareURL': '//h5.m.taobao.com/user_comment/comment_detail.html?rateId=1260006007986&sellerId=MX8RHvmQWPkx4vkguMFQbPm*eOm*hXm7-XF8Sv8kuP8QT&isEncode=true'}, 'skuMap': {}, 'structTagEndSize': '0', 'topRate': '0', 'userId': '0', 'userIndexURL': '', 'userMark': 'LdKXJtyGKx/SwERveonUlH3j9E7m9e24eFp5/qdqtuI=', 'userNick': '水**妞', 'userStar': '7', 'userStarPic': 'https://img.alicdn.com/imgextra/i4/O1CN01ZlCYMx1nbVriw6u0S_!!6000000005108-2-tps-92-45.png', 'userTagList': [{'extraInfo': {'level': '9'}, 'tagCode': 'credit', 'tagDesc': '信用等级', 'tagIconHeight': '27', 'tagIconPic': 'https://img.alicdn.com/imgextra/i4/O1CN01ZlCYMx1nbVriw6u0S_!!6000000005108-2-tps-92-45.png', 'tagIconWidth': '53'}]}], 'showInvite': 'false', 'skuFilter': 'true', 'timePeriodDesc': '近半年', 'total': '800', 'totalFuzzy': '800+', 'totalPage': '44', 'userType': '0'},
       'ret': ['SUCCESS::调用成功'],'traceId': '213e059517412462228283557e1329', 'v': '6.0'
       }
